/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PrivateLayoutRouteImport } from './pages/_private/_layout'
import { Route as AuthLayoutRouteImport } from './pages/_auth/_layout'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as PrivateAppLayoutRouteImport } from './pages/_private/_app/_layout'
import { Route as PrivateOnboardingIndexRouteImport } from './pages/_private/onboarding/index'
import { Route as PrivateAppTabsLayoutRouteImport } from './pages/_private/_app/_tabs/_layout'
import { Route as PrivateAppTabsMatchesIndexRouteImport } from './pages/_private/_app/_tabs/matches/index'
import { Route as PrivateAppTabsChatsIndexRouteImport } from './pages/_private/_app/_tabs/chats/index'
import { Route as PrivateAppTabsFeedIndexRouteImport } from './pages/_private/_app/_tabs/_feed/index'
import { Route as PrivateAppScreensProfileIndexRouteImport } from './pages/_private/_app/_screens/profile/index'
import { Route as PrivateAppScreensProfileUserIdRouteImport } from './pages/_private/_app/_screens/profile/$userId'
import { Route as PrivateAppScreensChatsIdRouteImport } from './pages/_private/_app/_screens/chats/$id'

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const PrivateAppLayoutRoute = PrivateAppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateOnboardingIndexRoute = PrivateOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateAppTabsLayoutRoute = PrivateAppTabsLayoutRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => PrivateAppLayoutRoute,
} as any)
const PrivateAppTabsMatchesIndexRoute =
  PrivateAppTabsMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => PrivateAppTabsLayoutRoute,
  } as any)
const PrivateAppTabsChatsIndexRoute =
  PrivateAppTabsChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => PrivateAppTabsLayoutRoute,
  } as any)
const PrivateAppTabsFeedIndexRoute = PrivateAppTabsFeedIndexRouteImport.update({
  id: '/_feed/',
  path: '/',
  getParentRoute: () => PrivateAppTabsLayoutRoute,
} as any)
const PrivateAppScreensProfileIndexRoute =
  PrivateAppScreensProfileIndexRouteImport.update({
    id: '/_screens/profile/',
    path: '/profile/',
    getParentRoute: () => PrivateAppLayoutRoute,
  } as any)
const PrivateAppScreensProfileUserIdRoute =
  PrivateAppScreensProfileUserIdRouteImport.update({
    id: '/_screens/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => PrivateAppLayoutRoute,
  } as any)
const PrivateAppScreensChatsIdRoute =
  PrivateAppScreensChatsIdRouteImport.update({
    id: '/_screens/chats/$id',
    path: '/chats/$id',
    getParentRoute: () => PrivateAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/onboarding': typeof PrivateOnboardingIndexRoute
  '/chats/$id': typeof PrivateAppScreensChatsIdRoute
  '/profile/$userId': typeof PrivateAppScreensProfileUserIdRoute
  '/profile': typeof PrivateAppScreensProfileIndexRoute
  '/': typeof PrivateAppTabsFeedIndexRoute
  '/chats': typeof PrivateAppTabsChatsIndexRoute
  '/matches': typeof PrivateAppTabsMatchesIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/onboarding': typeof PrivateOnboardingIndexRoute
  '/chats/$id': typeof PrivateAppScreensChatsIdRoute
  '/profile/$userId': typeof PrivateAppScreensProfileUserIdRoute
  '/profile': typeof PrivateAppScreensProfileIndexRoute
  '/': typeof PrivateAppTabsFeedIndexRoute
  '/chats': typeof PrivateAppTabsChatsIndexRoute
  '/matches': typeof PrivateAppTabsMatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_private/_app': typeof PrivateAppLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_private/_app/_tabs': typeof PrivateAppTabsLayoutRouteWithChildren
  '/_private/onboarding/': typeof PrivateOnboardingIndexRoute
  '/_private/_app/_screens/chats/$id': typeof PrivateAppScreensChatsIdRoute
  '/_private/_app/_screens/profile/$userId': typeof PrivateAppScreensProfileUserIdRoute
  '/_private/_app/_screens/profile/': typeof PrivateAppScreensProfileIndexRoute
  '/_private/_app/_tabs/_feed/': typeof PrivateAppTabsFeedIndexRoute
  '/_private/_app/_tabs/chats/': typeof PrivateAppTabsChatsIndexRoute
  '/_private/_app/_tabs/matches/': typeof PrivateAppTabsMatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/chats/$id'
    | '/profile/$userId'
    | '/profile'
    | '/'
    | '/chats'
    | '/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/chats/$id'
    | '/profile/$userId'
    | '/profile'
    | '/'
    | '/chats'
    | '/matches'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_private/_app'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_private/_app/_tabs'
    | '/_private/onboarding/'
    | '/_private/_app/_screens/chats/$id'
    | '/_private/_app/_screens/profile/$userId'
    | '/_private/_app/_screens/profile/'
    | '/_private/_app/_tabs/_feed/'
    | '/_private/_app/_tabs/chats/'
    | '/_private/_app/_tabs/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_private/_app': {
      id: '/_private/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateAppLayoutRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/onboarding/': {
      id: '/_private/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PrivateOnboardingIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/_app/_tabs': {
      id: '/_private/_app/_tabs'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateAppTabsLayoutRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
    '/_private/_app/_tabs/matches/': {
      id: '/_private/_app/_tabs/matches/'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof PrivateAppTabsMatchesIndexRouteImport
      parentRoute: typeof PrivateAppTabsLayoutRoute
    }
    '/_private/_app/_tabs/chats/': {
      id: '/_private/_app/_tabs/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof PrivateAppTabsChatsIndexRouteImport
      parentRoute: typeof PrivateAppTabsLayoutRoute
    }
    '/_private/_app/_tabs/_feed/': {
      id: '/_private/_app/_tabs/_feed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateAppTabsFeedIndexRouteImport
      parentRoute: typeof PrivateAppTabsLayoutRoute
    }
    '/_private/_app/_screens/profile/': {
      id: '/_private/_app/_screens/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateAppScreensProfileIndexRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
    '/_private/_app/_screens/profile/$userId': {
      id: '/_private/_app/_screens/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof PrivateAppScreensProfileUserIdRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
    '/_private/_app/_screens/chats/$id': {
      id: '/_private/_app/_screens/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof PrivateAppScreensChatsIdRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface PrivateAppTabsLayoutRouteChildren {
  PrivateAppTabsFeedIndexRoute: typeof PrivateAppTabsFeedIndexRoute
  PrivateAppTabsChatsIndexRoute: typeof PrivateAppTabsChatsIndexRoute
  PrivateAppTabsMatchesIndexRoute: typeof PrivateAppTabsMatchesIndexRoute
}

const PrivateAppTabsLayoutRouteChildren: PrivateAppTabsLayoutRouteChildren = {
  PrivateAppTabsFeedIndexRoute: PrivateAppTabsFeedIndexRoute,
  PrivateAppTabsChatsIndexRoute: PrivateAppTabsChatsIndexRoute,
  PrivateAppTabsMatchesIndexRoute: PrivateAppTabsMatchesIndexRoute,
}

const PrivateAppTabsLayoutRouteWithChildren =
  PrivateAppTabsLayoutRoute._addFileChildren(PrivateAppTabsLayoutRouteChildren)

interface PrivateAppLayoutRouteChildren {
  PrivateAppTabsLayoutRoute: typeof PrivateAppTabsLayoutRouteWithChildren
  PrivateAppScreensChatsIdRoute: typeof PrivateAppScreensChatsIdRoute
  PrivateAppScreensProfileUserIdRoute: typeof PrivateAppScreensProfileUserIdRoute
  PrivateAppScreensProfileIndexRoute: typeof PrivateAppScreensProfileIndexRoute
}

const PrivateAppLayoutRouteChildren: PrivateAppLayoutRouteChildren = {
  PrivateAppTabsLayoutRoute: PrivateAppTabsLayoutRouteWithChildren,
  PrivateAppScreensChatsIdRoute: PrivateAppScreensChatsIdRoute,
  PrivateAppScreensProfileUserIdRoute: PrivateAppScreensProfileUserIdRoute,
  PrivateAppScreensProfileIndexRoute: PrivateAppScreensProfileIndexRoute,
}

const PrivateAppLayoutRouteWithChildren =
  PrivateAppLayoutRoute._addFileChildren(PrivateAppLayoutRouteChildren)

interface PrivateLayoutRouteChildren {
  PrivateAppLayoutRoute: typeof PrivateAppLayoutRouteWithChildren
  PrivateOnboardingIndexRoute: typeof PrivateOnboardingIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateAppLayoutRoute: PrivateAppLayoutRouteWithChildren,
  PrivateOnboardingIndexRoute: PrivateOnboardingIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
