/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PrivateLayoutRouteImport } from './pages/_private/_layout'
import { Route as AuthLayoutRouteImport } from './pages/_auth/_layout'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as PrivateAppLayoutRouteImport } from './pages/_private/_app/_layout'
import { Route as PrivateOnboardingIndexRouteImport } from './pages/_private/onboarding/index'
import { Route as PrivateAppProfileIndexRouteImport } from './pages/_private/_app/profile/index'
import { Route as PrivateAppMeetsIndexRouteImport } from './pages/_private/_app/meets/index'
import { Route as PrivateAppChatIndexRouteImport } from './pages/_private/_app/chat/index'
import { Route as PrivateAppFeedIndexRouteImport } from './pages/_private/_app/_feed/index'
import { Route as PrivateAppProfileUserIdRouteImport } from './pages/_private/_app/profile/$userId'

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const PrivateAppLayoutRoute = PrivateAppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateOnboardingIndexRoute = PrivateOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateAppProfileIndexRoute = PrivateAppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PrivateAppLayoutRoute,
} as any)
const PrivateAppMeetsIndexRoute = PrivateAppMeetsIndexRouteImport.update({
  id: '/meets/',
  path: '/meets/',
  getParentRoute: () => PrivateAppLayoutRoute,
} as any)
const PrivateAppChatIndexRoute = PrivateAppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => PrivateAppLayoutRoute,
} as any)
const PrivateAppFeedIndexRoute = PrivateAppFeedIndexRouteImport.update({
  id: '/_feed/',
  path: '/',
  getParentRoute: () => PrivateAppLayoutRoute,
} as any)
const PrivateAppProfileUserIdRoute = PrivateAppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => PrivateAppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/onboarding': typeof PrivateOnboardingIndexRoute
  '/profile/$userId': typeof PrivateAppProfileUserIdRoute
  '/': typeof PrivateAppFeedIndexRoute
  '/chat': typeof PrivateAppChatIndexRoute
  '/meets': typeof PrivateAppMeetsIndexRoute
  '/profile': typeof PrivateAppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/onboarding': typeof PrivateOnboardingIndexRoute
  '/profile/$userId': typeof PrivateAppProfileUserIdRoute
  '/': typeof PrivateAppFeedIndexRoute
  '/chat': typeof PrivateAppChatIndexRoute
  '/meets': typeof PrivateAppMeetsIndexRoute
  '/profile': typeof PrivateAppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_private/_app': typeof PrivateAppLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_private/onboarding/': typeof PrivateOnboardingIndexRoute
  '/_private/_app/profile/$userId': typeof PrivateAppProfileUserIdRoute
  '/_private/_app/_feed/': typeof PrivateAppFeedIndexRoute
  '/_private/_app/chat/': typeof PrivateAppChatIndexRoute
  '/_private/_app/meets/': typeof PrivateAppMeetsIndexRoute
  '/_private/_app/profile/': typeof PrivateAppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/profile/$userId'
    | '/'
    | '/chat'
    | '/meets'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/profile/$userId'
    | '/'
    | '/chat'
    | '/meets'
    | '/profile'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_private/_app'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_private/onboarding/'
    | '/_private/_app/profile/$userId'
    | '/_private/_app/_feed/'
    | '/_private/_app/chat/'
    | '/_private/_app/meets/'
    | '/_private/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_private/_app': {
      id: '/_private/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateAppLayoutRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/onboarding/': {
      id: '/_private/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PrivateOnboardingIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/_app/profile/': {
      id: '/_private/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateAppProfileIndexRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
    '/_private/_app/meets/': {
      id: '/_private/_app/meets/'
      path: '/meets'
      fullPath: '/meets'
      preLoaderRoute: typeof PrivateAppMeetsIndexRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
    '/_private/_app/chat/': {
      id: '/_private/_app/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof PrivateAppChatIndexRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
    '/_private/_app/_feed/': {
      id: '/_private/_app/_feed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateAppFeedIndexRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
    '/_private/_app/profile/$userId': {
      id: '/_private/_app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof PrivateAppProfileUserIdRouteImport
      parentRoute: typeof PrivateAppLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface PrivateAppLayoutRouteChildren {
  PrivateAppProfileUserIdRoute: typeof PrivateAppProfileUserIdRoute
  PrivateAppFeedIndexRoute: typeof PrivateAppFeedIndexRoute
  PrivateAppChatIndexRoute: typeof PrivateAppChatIndexRoute
  PrivateAppMeetsIndexRoute: typeof PrivateAppMeetsIndexRoute
  PrivateAppProfileIndexRoute: typeof PrivateAppProfileIndexRoute
}

const PrivateAppLayoutRouteChildren: PrivateAppLayoutRouteChildren = {
  PrivateAppProfileUserIdRoute: PrivateAppProfileUserIdRoute,
  PrivateAppFeedIndexRoute: PrivateAppFeedIndexRoute,
  PrivateAppChatIndexRoute: PrivateAppChatIndexRoute,
  PrivateAppMeetsIndexRoute: PrivateAppMeetsIndexRoute,
  PrivateAppProfileIndexRoute: PrivateAppProfileIndexRoute,
}

const PrivateAppLayoutRouteWithChildren =
  PrivateAppLayoutRoute._addFileChildren(PrivateAppLayoutRouteChildren)

interface PrivateLayoutRouteChildren {
  PrivateAppLayoutRoute: typeof PrivateAppLayoutRouteWithChildren
  PrivateOnboardingIndexRoute: typeof PrivateOnboardingIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateAppLayoutRoute: PrivateAppLayoutRouteWithChildren,
  PrivateOnboardingIndexRoute: PrivateOnboardingIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
